blank_issues_enabled: false
contact_links:
  - name: Community Support & Questions
    url: https://discord.gg/tpeBPy46hf
    about: Join the Discord if you have questions or want to discuss this mod with the community.
  - name: Partnership Request
    url: https://discordapp.com/users/394185816370315276
    about: Contact me on Discord to discuss a partnership.