name: Version Incrementer

on:
  push:
    branches:
      - master

jobs:
  version-incrementer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Get current version
        id: get_version
        run: |
          current_version=$(grep 'version = ' src/main/java/com/SwingTheVine/QSAND/ModInfo.java | cut -d '"' -f2)
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

      - name: Version increment
        id: version_increment
        run: |
          current_version=${{ steps.get_version.outputs.current_version }}
          major=$(echo $current_version | cut -d'.' -f1)
          minor=$(echo $current_version | cut -d'.' -f2)
          patch=$(echo $current_version | cut -d'.' -f3)
          new_minor=$((minor + 1))
          new_version="$major.$new_minor.0"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version in file
        run: |
          new_version=${{ steps.increment_version.outputs.new_version }}
          sed -i 's/version = "[^"]*"/version = "'$new_version'"/' src/main/java/com/SwingTheVine/QSAND/ModInfo.java

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/main/java/com/SwingTheVine/QSAND/ModInfo.java
          git commit -m "Incremented version to ${{ steps.increment_version.outputs.new_version }}"
          git push
